site_name: "AnnotSv"
site_description: "Annotation and Ranking of Structural Variation "
site_url: "https://lgmgeo.github.io/AnnotSV"
repo_url: "https://github.com/lgmgeo/AnnotSV"
repo_name: "lgmgeo/AnnotSV"
site_dir: "site"

nav:
  - Home:
    - Overview: index.md
    - Changelog: changelog.md
  - Development:
    - Contributing: contributing.md
    - Code of Conduct: code_of_conduct.md

theme:
  name: material
  palette:
    primary: deep purple
    accent: teal
  font:
    text: Open Sans
    code: Fira Code


markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "#"

plugins:
  - search
